export default interface IPlayer {
  high_school?: string;
  age?: number;
  college?: string;
  first_name?: string;
  search_first_name?: string;
  last_name?: string;
  pandascore_id?: string | number;
  stats_id?: number;
  practice_description?: string;
  injury_body_part?: string;
  practice_participation?: string;
  active?: boolean;
  height?: string;
  opta_id?: string | number;
  swish_id?: number;
  metadata?: Record<string, string>;
  years_exp?: number;
  player_id: string;
  competitions?: string[];
  status?: string;
  fantasy_data_id?: number;
  birth_date?: string;
  weight?: string;
  injury_notes?: string;
  fantasy_positions?: string[];
  oddsjam_id?: string;
  search_last_name?: string;
  sportradar_id?: string;
  search_rank?: number;
  yahoo_id?: number;
  rotoworld_id?: number;
  news_updated?: number;
  birth_state?: string;
  hashtag?: string;
  team_abbr?: string;
  gsis_id?: string | number;
  team_changed_at?: number;
  search_full_name?: string;
  rotowire_id?: number;
  depth_chart_order?: number;
  depth_chart_position?: string;
  birth_country?: string;
  espn_id?: number;
  position?: string;
  injury_status?: string;
  team?: string;
  full_name?: string;
  birth_city?: string;
  sport?: string;
  injury_start_date?: string;
  number?: number;
}
